// <auto-generated />
using System;
using ApiGestaoCursos.Infra.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiGestaoCursos.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240209023113_Update_Aluno_Curso")]
    partial class UpdateAlunoCurso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiGestaoCursos.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ATIVO");

                    b.Property<Guid?>("CursoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("Data_Atualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("Data_Criacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_NASCIMENTO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("ALUNO", (string)null);
                });

            modelBuilder.Entity("ApiGestaoCursos.Domain.Entities.Curso", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("ID");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime?>("Data_Atualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("Data_Criacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTime?>("Data_Fim")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_FIM");

                    b.Property<DateTime?>("Data_Inicio")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_INICIO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("CURSO", (string)null);
                });

            modelBuilder.Entity("ApiGestaoCursos.Domain.Entities.Aluno", b =>
                {
                    b.HasOne("ApiGestaoCursos.Domain.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Curso");
                });
#pragma warning restore 612, 618
        }
    }
}
